name: PHP Linting
on: pull_request
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@2.0.0
          with:
            preset: psr12
            verboseMode: true
            testMode: false
            configPath: "pint.json"
            pintVersion: 1.8.0
        - name: Commit changed files
          uses: stefanzweifel/git-auto-commit-action@v2.3.0
          with:
            commit_message: Apply automatic changes
            branch: ${{ github.head_ref }}

            # Optional git params
            commit_options: '--no-verify --signoff'

            # Optional glob pattern of files which should be added to the commit
            file_pattern: src/\*.js
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
